services:
  # Backend Django API
  - type: web
    name: skillswap-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py create_demo_users"
    startCommand: "gunicorn skillswap_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: skillswap-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "skillswap-backend-8k91.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://skillswap-frontend-31tg.onrender.com"

  # Frontend React App
  - type: web
    name: skillswap-frontend
    env: node
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: "npm install && NODE_OPTIONS=--openssl-legacy-provider npm run build"
    startCommand: "node_modules/.bin/serve -s build -p $PORT"
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_OPTIONS
        value: "--openssl-legacy-provider"
      - key: REACT_APP_API_URL
        value: "https://skillswap-backend-8k91.onrender.com/api"

# Database
databases:
  - name: skillswap-db
    plan: free
    region: oregon
    databaseName: skillswap
    user: skillswap
